[package]
name = "osurate"
version = "0.1.0"
authors = ["LunarCoffee <lunarcoffee.pjc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lame = "0.1.3"
minimp3 = "0.5.1"
rubato = "0.7.0"
